### ISSUE TITLE
[Bug] Can't install with thunderstore mod manager

### ISSUE THREAD

**Issue by MathiusXII** [ButteryStancakes/EnemySoundFixes#1]
Error
Mod does not exist
Unable to resolve ButteryStancakes-EnemySoundFixes to a suitable Thunderstore mod

**Comment by ButteryStancakes** [comment]
This is a Thunderstore issue and out of my control. It should be available now, though (sometimes it just takes an hour or so to appear)

**Comment by MathiusXII** [comment]
Oh ok yeah it's fine now. Does that just happen when a mod is first posted on thunderstore?
