### ISSUE TITLE
[Request] Change mimic footstep volume

### ISSUE THREAD

**Issue by MathiusXII** [ButteryStancakes/EnemySoundFixes#3]
I use mods that make mimics blend in with players, but their footsteps are so loud you can tell they're fake. You can also hear them coming from a mile away.

**Comment by ButteryStancakes** [comment]
Definitely a possibility - I have thought about this. Will probably make it a config setting if I go forward with it

**Comment by ButteryStancakes** [comment]
Implemented in v1.5.0
